using System.Collections.Generic;

namespace Ircuitry.Irc;

/// <summary>
/// Maps IRC numeric replies to their RPL_/ERR_ names and a short human description, per
/// modern.ircdocs.horse. Used by the event console + read-only IRC view so "433" reads as
/// "433 ERR_NICKNAMEINUSE - Nickname already in use" instead of a bare number.
/// </summary>
public static class IrcNumerics
{
    /// <summary>The RPL_/ERR_ name for a numeric, or null if unknown.</summary>
    public static string? Name(int n) => Table.TryGetValue(n, out var v) ? v.name : null;

    /// <summary>A short description for a numeric, or "" if unknown.</summary>
    public static string Describe(int n) => Table.TryGetValue(n, out var v) ? v.desc : "";

    /// <summary>True for ERR_* numerics (the 4xx/5xx error range and a few SASL errors).</summary>
    public static bool IsError(int n) => Table.TryGetValue(n, out var v) && v.name.StartsWith("ERR_");

    private static readonly Dictionary<int, (string name, string desc)> Table = new()
    {
        [1] = ("RPL_WELCOME", "First message sent after successful client registration"),
        [2] = ("RPL_YOURHOST", "Server identification and version information"),
        [3] = ("RPL_CREATED", "Server creation date"),
        [4] = ("RPL_MYINFO", "Server name, version, user modes, and channel modes"),
        [5] = ("RPL_ISUPPORT", "Server capability advertisement"),
        [10] = ("RPL_BOUNCE", "Server redirection notice"),
        [212] = ("RPL_STATSCOMMANDS", "Command usage statistics"),
        [219] = ("RPL_ENDOFSTATS", "End of statistics output"),
        [221] = ("RPL_UMODEIS", "Current user modes"),
        [242] = ("RPL_STATSUPTIME", "Server uptime information"),
        [251] = ("RPL_LUSERCLIENT", "Local and global user counts"),
        [252] = ("RPL_LUSEROP", "Number of IRC operators online"),
        [253] = ("RPL_LUSERUNKNOWN", "Unknown connection count"),
        [254] = ("RPL_LUSERCHANNELS", "Number of channels"),
        [255] = ("RPL_LUSERME", "Server-specific user statistics"),
        [256] = ("RPL_ADMINME", "Server administrator location"),
        [257] = ("RPL_ADMINLOC1", "Administrator location first line"),
        [258] = ("RPL_ADMINLOC2", "Administrator location second line"),
        [259] = ("RPL_ADMINEMAIL", "Administrator email address"),
        [263] = ("RPL_TRYAGAIN", "Server temporarily unavailable"),
        [265] = ("RPL_LOCALUSERS", "Local user statistics"),
        [266] = ("RPL_GLOBALUSERS", "Global user statistics"),
        [276] = ("RPL_WHOISCERTFP", "User certificate fingerprint"),
        [300] = ("RPL_NONE", "Null reply"),
        [301] = ("RPL_AWAY", "User away status message"),
        [302] = ("RPL_USERHOST", "User host information"),
        [305] = ("RPL_UNAWAY", "User no longer away"),
        [306] = ("RPL_NOWAWAY", "User marked as away"),
        [307] = ("RPL_WHOISREGNICK", "User has registered nickname"),
        [311] = ("RPL_WHOISUSER", "WHOIS user information"),
        [312] = ("RPL_WHOISSERVER", "WHOIS server information"),
        [313] = ("RPL_WHOISOPERATOR", "User is an IRC operator"),
        [314] = ("RPL_WHOWASUSER", "Historical user information"),
        [315] = ("RPL_ENDOFWHO", "End of WHO response"),
        [317] = ("RPL_WHOISIDLE", "User idle time information"),
        [318] = ("RPL_ENDOFWHOIS", "End of WHOIS response"),
        [319] = ("RPL_WHOISCHANNELS", "User channel membership list"),
        [320] = ("RPL_WHOISSPECIAL", "User special status"),
        [321] = ("RPL_LISTSTART", "Start of channel list"),
        [322] = ("RPL_LIST", "Channel list entry"),
        [323] = ("RPL_LISTEND", "End of channel list"),
        [324] = ("RPL_CHANNELMODEIS", "Current channel modes"),
        [329] = ("RPL_CREATIONTIME", "Channel creation timestamp"),
        [330] = ("RPL_WHOISACCOUNT", "User account name"),
        [331] = ("RPL_NOTOPIC", "Channel has no topic"),
        [332] = ("RPL_TOPIC", "Current channel topic"),
        [333] = ("RPL_TOPICWHOTIME", "Topic setter and timestamp"),
        [336] = ("RPL_INVITELIST", "User invite list entry"),
        [337] = ("RPL_ENDOFINVITELIST", "End of invite list"),
        [338] = ("RPL_WHOISACTUALLY", "User actual hostname and IP"),
        [341] = ("RPL_INVITING", "User invitation confirmation"),
        [346] = ("RPL_INVEXLIST", "Channel invite-exception entry"),
        [347] = ("RPL_ENDOFINVEXLIST", "End of invite-exception list"),
        [348] = ("RPL_EXCEPTLIST", "Channel exception list entry"),
        [349] = ("RPL_ENDOFEXCEPTLIST", "End of exception list"),
        [351] = ("RPL_VERSION", "Server version information"),
        [352] = ("RPL_WHOREPLY", "WHO command response entry"),
        [353] = ("RPL_NAMREPLY", "Channel member names list"),
        [364] = ("RPL_LINKS", "Server link information"),
        [365] = ("RPL_ENDOFLINKS", "End of server links"),
        [366] = ("RPL_ENDOFNAMES", "End of channel names"),
        [367] = ("RPL_BANLIST", "Channel ban list entry"),
        [368] = ("RPL_ENDOFBANLIST", "End of ban list"),
        [369] = ("RPL_ENDOFWHOWAS", "End of historical user data"),
        [371] = ("RPL_INFO", "Server information line"),
        [372] = ("RPL_MOTD", "Message of the day line"),
        [374] = ("RPL_ENDOFINFO", "End of server information"),
        [375] = ("RPL_MOTDSTART", "Start of message of the day"),
        [376] = ("RPL_ENDOFMOTD", "End of message of the day"),
        [378] = ("RPL_WHOISHOST", "User hostname and connection IP"),
        [379] = ("RPL_WHOISMODES", "User modes information"),
        [381] = ("RPL_YOUREOPER", "Operator status granted"),
        [382] = ("RPL_REHASHING", "Server configuration reload"),
        [391] = ("RPL_TIME", "Server time response"),
        [400] = ("ERR_UNKNOWNERROR", "Unknown error condition"),
        [401] = ("ERR_NOSUCHNICK", "Nickname does not exist"),
        [402] = ("ERR_NOSUCHSERVER", "Server does not exist"),
        [403] = ("ERR_NOSUCHCHANNEL", "Channel does not exist"),
        [404] = ("ERR_CANNOTSENDTOCHAN", "Cannot message channel"),
        [405] = ("ERR_TOOMANYCHANNELS", "User joined too many channels"),
        [406] = ("ERR_WASNOSUCHNICK", "Historical nickname does not exist"),
        [409] = ("ERR_NOORIGIN", "PING requires origin parameter"),
        [411] = ("ERR_NORECIPIENT", "No message recipient specified"),
        [412] = ("ERR_NOTEXTTOSEND", "No message text provided"),
        [417] = ("ERR_INPUTTOOLONG", "Message exceeds length limit"),
        [421] = ("ERR_UNKNOWNCOMMAND", "Unknown IRC command"),
        [422] = ("ERR_NOMOTD", "Server has no message of the day"),
        [431] = ("ERR_NONICKNAMEGIVEN", "No nickname parameter given"),
        [432] = ("ERR_ERRONEUSNICKNAME", "Invalid nickname characters"),
        [433] = ("ERR_NICKNAMEINUSE", "Nickname already in use"),
        [436] = ("ERR_NICKCOLLISION", "Nickname collision detected"),
        [441] = ("ERR_USERNOTINCHANNEL", "User not in channel"),
        [442] = ("ERR_NOTONCHANNEL", "Client not in channel"),
        [443] = ("ERR_USERONCHANNEL", "User already in channel"),
        [451] = ("ERR_NOTREGISTERED", "Client not yet registered"),
        [461] = ("ERR_NEEDMOREPARAMS", "Insufficient command parameters"),
        [462] = ("ERR_ALREADYREGISTERED", "Client already registered"),
        [464] = ("ERR_PASSWDMISMATCH", "Connection password incorrect"),
        [465] = ("ERR_YOUREBANNEDCREEP", "Client banned from server"),
        [471] = ("ERR_CHANNELISFULL", "Channel has reached user limit"),
        [472] = ("ERR_UNKNOWNMODE", "Unknown mode character"),
        [473] = ("ERR_INVITEONLYCHAN", "Channel is invite-only"),
        [474] = ("ERR_BANNEDFROMCHAN", "Client banned from channel"),
        [475] = ("ERR_BADCHANNELKEY", "Channel key is incorrect"),
        [476] = ("ERR_BADCHANMASK", "Invalid channel mask syntax"),
        [481] = ("ERR_NOPRIVILEGES", "User lacks server operator privileges"),
        [482] = ("ERR_CHANOPRIVSNEEDED", "Channel operator privileges required"),
        [483] = ("ERR_CANTKILLSERVER", "Cannot kill server connections"),
        [491] = ("ERR_NOOPERHOST", "User not from valid operator host"),
        [501] = ("ERR_UMODEUNKNOWNFLAG", "Unknown user mode flag"),
        [502] = ("ERR_USERSDONTMATCH", "Cannot modify other user modes"),
        [524] = ("ERR_HELPNOTFOUND", "Help topic not available"),
        [525] = ("ERR_INVALIDKEY", "Invalid key provided"),
        [670] = ("RPL_STARTTLS", "TLS connection established"),
        [671] = ("RPL_WHOISSECURE", "User connection is secure"),
        [691] = ("ERR_STARTTLS", "TLS connection failed"),
        [696] = ("ERR_INVALIDMODEPARAM", "Invalid mode parameter"),
        [704] = ("RPL_HELPSTART", "Help response starting"),
        [705] = ("RPL_HELPTXT", "Help response text line"),
        [706] = ("RPL_ENDOFHELP", "Help response ending"),
        [723] = ("ERR_NOPRIVS", "Insufficient operator privileges"),
        [900] = ("RPL_LOGGEDIN", "SASL authentication successful login"),
        [901] = ("RPL_LOGGEDOUT", "SASL logout successful"),
        [902] = ("ERR_NICKLOCKED", "Nick locked during SASL"),
        [903] = ("RPL_SASLSUCCESS", "SASL authentication completed"),
        [904] = ("ERR_SASLFAIL", "SASL authentication failed"),
        [905] = ("ERR_SASLTOOLONG", "SASL message too long"),
        [906] = ("ERR_SASLABORTED", "SASL authentication aborted"),
        [907] = ("ERR_SASLALREADY", "SASL already in progress"),
        [908] = ("RPL_SASLMECHS", "SASL mechanisms list"),
    };
}
